services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    - "--storage.tsdb.path=/prometheus"
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - /bin/bash:/bin/bash
    network_mode: "host"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
    - '3000:3000'
    volumes:
    - grafana-storage:/var/lib/grafana
    - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
    - GF_SECURITY_ADMIN_USER=admin 
    - GF_SECURITY_ADMIN_PASSWORD=admin
    - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting
    depends_on:
    - prometheus
    network_mode: "host"
    
volumes:
  grafana-storage: {}
