global:
  scrape_interval: 5s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['localhost:9201', 'omega-b.gat.com:9100', 'irisb.gat.com:9100']

#gcc -o write_metrics write_metrics.c && ./write_metrics & 