global:
  scrape_interval: 60s

scrape_configs:
- job_name: node
  static_configs:
  - targets: ['irisb.gat.com:9100']
  #- targets: ['localhost:9201', 'omega-b.gat.com:9100', 'irisb.gat.com:9100']
  metric_relabel_configs:
  - source_labels: [__name__]
    regex: 'cpu_usage|ram_usage|ncpus'
    action: keep

#gcc -o write_metrics write_metrics.c && ./write_metrics &